### ISSUE TITLE
Plotly Dashboard Optimizations

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#32]
This is a Super Issue detailing all dashboard optimizations that need to be completed.

Plotly dashboard is known for having performance issues and we need to set up a variety of optimizations to improve UX.

Tasks:
- [ ] Intermediary Processing step
- [ ] Flask Caching (fs)
- [ ] Setup Redis on AWS
- [ ] Flask Caching (Redis)
- [ ] Background Callbacks (Celery)
