### ISSUE TITLE
AWS Lambda - Data Processing and Aggregation

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#5]
Write an AWS Lambda function that will process incoming data and output "snapshots" of data from a collection of files. Accept data as post requests and work with #4 for networking. Upload these snapshots into MongoDB.

This processing should be done away from the pi. If we ever get a sim card, it will allow us to create real-time dashboards.

Get the AWS Account information from Noel and setup a lambda function.

Ideally take this if you have cloud experience or want to learn more about it.

## Tasks
- [ ] Create a MongoDB account for DFR
- [ ] Create REST API for sending to MongoDB
- [ ] Set up new AWS lambda function in AWS

**Comment by Squidtoon99** [comment]
Future progress tracked in Star Stream
